"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.materials = exports.shape_functions = exports.canvas_functions = exports.draw_scene3D = exports.data_types = void 0;
var data_types = require("./types");
exports.data_types = data_types;
var draw_helpers_1 = require("./draw_helpers");
Object.defineProperty(exports, "draw_scene3D", { enumerable: true, get: function () { return draw_helpers_1.draw_scene3D; } });
var canvas_functions = require("./canvas_helpers");
exports.canvas_functions = canvas_functions;
var shape_functions = require("./shape_helpers");
exports.shape_functions = shape_functions;
var materials = require("./material_helpers");
exports.materials = materials;
